### ISSUE TITLE
Node.js: "TypeError: Only absolute URLs are supported" when using a local checkpoint path

### ISSUE THREAD

**Issue by JuanuMusic** [magenta/magenta-js#470]
Hi!
I'm implementing magenta.js using Node and I'm getting the error upon calling the initialize() when initialized with a local path:
`TypeError: Only absolute URLs are supported`

This is the full Error log:
```
UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (D:\Code\Repos\JuanuMusic\musicator\node_modules\node-fetch\lib\index.js:1284:9)
    at D:\Code\Repos\JuanuMusic\musicator\node_modules\node-fetch\lib\index.js:1370:19
    at new Promise (<anonymous>)
    at fetch (D:\Code\Repos\JuanuMusic\musicator\node_modules\node-fetch\lib\index.js:1367:9)
    at p.initialize (D:\Code\Repos\JuanuMusic\musicator\node_modules\@magenta\music\node\music_rnn.js:1:112313)
    at Object.getBasicRnn (D:\Code\Repos\JuanuMusic\musicator\services\musicRnnService.js:13:32)
    at D:\Code\Repos\JuanuMusic\musicator\routes\music.js:7:21
    at Layer.handle [as handle_request] (D:\Code\Repos\JuanuMusic\musicator\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Code\Repos\JuanuMusic\musicator\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Code\Repos\JuanuMusic\musicator\node_modules\express\lib\router\route.js:112:3)
```

and this is the code that's throwing the error:
```
const music_rnn = require('@magenta/music/node/music_rnn');

/// Singleton instance
let basic_rnn_instance;

const musicRnnService = {
    /**
     * Returns the model instance
     */
    async getBasicRnn() {
        // Singleton
        if (!basic_rnn_instance) {

            // Get the model checkpoint from a local path
            const modelCheckPoint = '../checkpoints/basic_rnn.mag';
            basic_rnn_instance = new music_rnn.MusicRNN(modelCheckPoint);

            // Initialize
            basic_rnn_instance.initialize()
                .then(() => console.log("Initialized"))
                .then(samples => {
                    console.log(samples);
                });

        }
        return basic_rnn_instance;

    }
};

module.exports = musicRnnService;
```

Am I doing something wrong or are local checkpoint paths not allowed?

**Comment by Seanitzel** [comment]
Static paths mean either a URL or '/...' .

You should put your model in the public or static folder of your project(which ever your project uses), and use '/my_model' for the checkpoint.

**Comment by notwaldorf** [comment]
Yeah, I think @Seanitzel's got it!

**Comment by notwaldorf** [comment]
(marking as resolved, but please re-open if the fix doesn't work for you)
