### ISSUE TITLE
Error building magenta-js/music for node with tfjs-core 1.7.4

### ISSUE THREAD

**Issue by divisiondeariza** [magenta/magenta-js#494]
I was trying to build magenta for node with latest 1.x.x tfjs-core version (1.7.4, which is chosen by default when you run `npm install` inside magenta-js/music dir) but i got this error when I tried to use it in a simple gist:

```
    environment_1.env().setPlatform('node', new PlatformNode());
                        ^

TypeError: environment_1.env(...).setPlatform is not a function
    at Object.<anonymous> (/home/emmanuel/live-code/magenta-rest/lib/magenta-js/music/node_modules/@tensorflow/tfjs-core/dist/platforms/platform_node.js:77:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/emmanuel/live-code/magenta-rest/lib/magenta-js/music/node_modules/@tensorflow/tfjs-core/dist/index.js:46:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```
I think it's related to this [line in tfjs repo](https://github.com/tensorflow/tfjs/blob/7ccca47637b6c9125ba03b7bd205bda029842961/tfjs-core/src/platforms/platform_node.ts#L85)

When I installed tfjs-core 1.1.2 (`npm i @tensorflow/tfjs@1.1.2`) worked just well.

Maybe it's just a matter of changing [this line in package.json ](https://github.com/magenta/magenta-js/blob/b149ce62e7b58075e7177d3b33be123fb6706144/music/package.json#L11) from 
`    "@tensorflow/tfjs": "^1.1.2",`
to
`    "@tensorflow/tfjs": "1.1.2",`

**Comment by notwaldorf** [comment]
What do you mean by "building magenta for node"? what is the command that you're running?

**Comment by divisiondeariza** [comment]
I cloned the repo, then I ran "npm install" then "npm run-script build:node", it didn't work well until I fixed the dependencies in the package.json file to the "1.1.2" version. It looks like api in tensorflow 1.7.4 is not backward compatible with 1.1.2 version.

**Comment by notwaldorf** [comment]
Closing this issue as stale because it has not had recent activity. I tried building this recently and it works (and we also just updated tensorflow to 2.7). If you have any more updates, please comment on this thread or open a new issue with more details. Thanks!
