### ISSUE TITLE
"Error: Cannot use offline audio context in Node.js" when using OnsetsAndFrames

### ISSUE THREAD

**Issue by daorren** [magenta/magenta-js#496]
I'm trying to use transcription model in Node.js, here's my script:
```js
const fs = require('fs');
const transcription = require('@magenta/music/node/transcription');

const model = new transcription.OnsetsAndFrames('https://storage.googleapis.com/magentadata/js/checkpoints/transcription/onsets_frames_uni');
console.log('----');
const data = fs.readFileSync('/mypath/20.wav');
console.log(data instanceof Buffer);
model
  .initialize()
  .then(() => console.log('isInitialized', model.isInitialized()))
  .then(() => model.transcribeFromAudioBuffer(data).then((ns) => console.log('finished', ns)));

```
And I get this error, which I think from ` new transcription.OnsetsAndFrames` line
```
Error: Cannot use offline audio context in Node.js
    at a (/Users/jojo/work/work@mint/scripts/node_modules/@magenta/music/node/transcription.js:1:2240)
    at Object.<anonymous> (/Users/jojo/work/work@mint/scripts/node_modules/@magenta/music/node/transcription.js:1:2664)
    at n (/Users/jojo/work/work@mint/scripts/node_modules/@magenta/music/node/transcription.js:1:382)
    at Module.<anonymous> (/Users/jojo/work/work@mint/scripts/node_modules/@magenta/music/node/transcription.js:1:83106)
    at n (/Users/jojo/work/work@mint/scripts/node_modules/@magenta/music/node/transcription.js:1:382)
    at /Users/jojo/work/work@mint/scripts/node_modules/@magenta/music/node/transcription.js:1:1181
    at /Users/jojo/work/work@mint/scripts/node_modules/@magenta/music/node/transcription.js:1:1191
    at /Users/jojo/work/work@mint/scripts/node_modules/@magenta/music/node/transcription.js:1:143
```
Any idea to fix this?

**Comment by notwaldorf** [comment]
Unfortunately, this is kind of working as in intended 😢 . OfflineAudioContext is the thing that manipulates the audio buffer, but that is not available in Node. There are some polyfills for audio contexts for Node, but it would involve a lot of refactoring of the existing code to make sure they work correctly, have all the functionality etc.

**Comment by daorren** [comment]
Thank you so much for responding!
Guess I have to find some other solution
