### ISSUE TITLE
"TypeError: Only absolute URLs are supported" even with absolute local path

### ISSUE THREAD

**Issue by JanZaion** [magenta/magenta-js#576]
Hello,

Im trying to run Melody RNN checkpoint localy in node with the following code:

```
const mm = require('@magenta/music/node/music_rnn');

(async () => {
  const checkpoint = 'C:/Users/zajic/Desktop/melody-with-magenta/checkpoints/melody_rnn/';
  const RNN = new mm.MusicRNN(checkpoint);
  await RNN.initialize();
})();
```
and I keep geting 

```
(node:11908) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\zajic\Desktop\melody-with-magenta\node_modules\node-fetch\lib\index.js:1305:9)  
    at C:\Users\zajic\Desktop\melody-with-magenta\node_modules\node-fetch\lib\index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\zajic\Desktop\melody-with-magenta\node_modules\node-fetch\lib\index.js:1407:9)
    at l.initialize (C:\Users\zajic\Desktop\melody-with-magenta\node_modules\@magenta\music\node\music_rnn.js:1:114470)
    at C:\Users\zajic\Desktop\melody-with-magenta\pt.js:6:13
    at Object.<anonymous> (C:\Users\zajic\Desktop\melody-with-magenta\pt.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
```

Even though I have provided absolute path, I keep geting this error.

I have looked over [issue 470](https://github.com/magenta/magenta-js/issues/470), but it looks like I'm unable to follow instructions provided there.

Thanks for your help in advance!

**Comment by jjannone** [comment]
I tried to use `file://` as suggested and I get the error: `TypeError: Only HTTP(S) protocols are supported` - anyone have another approach to referencing local files?
